<template>
  <div class="relative overflow-hidden">
    <div class="mx-auto max-w-prose text-lg">
      <PageHeader :heading="header" />
      <div v-for="item in about" :key="item.header" class="my-10">
        <h3 v-if="item.header"> {{ item.header }} </h3>
        <p class="mt-4 text-white">{{ item.subHeader }}</p>
      </div>
    </div>
  </div>
</template>

<script setup>
import PageHeader from './PageHeader.vue';

const header =
{
  header: "What's This Then?",
  subHeader: "Gallry.Art is an image gallery based on Node and Vue.",
}

const about = [
  {
    // header: "What's This Then?",
    subHeader: "Gallry.Art is an image gallery based on Node and Vue. It's a work in progress, but the basic functionality is there. You can browse the images, and you can download them. You can also create an account and upload your own images.",
  },
  {
    header: "What's This Then?",
    subHeader: "The images are generated by AI, so they're all unique. They're also free to use, so you can use them for whatever you want.",
  },
  {
    subHeader: "As artificial intelligence continues to evolve, so too does the way in which it can generate images. The first ai generated images were simple and often crudely made, but as the technology has progressed, so too has the quality of the images that can be produced. These days, there are entire galleries dedicated to ai generated art"
  },
  {
    header: "Get Your Own Gallry",
    subHeader: "We believe that by providing a place for artists to share their visions, we can help make the world a more beautiful and inspiring place. If you'd like to create your own gallery, you can get started by clicking here",
  },
  {
    // header: "Get Your Own Gallry",
    subHeader: "Looking at the current state of AI-generated images, it's easy to see why some people are concerned about their future. However, it's important to remember that these images are still in their infancy.",
  },
]

</script>