<template>
  <!-- {{ content }}}-->
  <!-- id = {{ catRoute }}  -->
  <ContentHeading :heading="header" />

  <div class="grid place-items-center mt-5">
    <main class="mx-auto max-w-max sm:flex">
      <TheGallery :id="catRoute" />
    </main>
  </div>
  
</template>

<script setup>
import TheGallery from "../components/galleries/TheGallery.vue";
import ContentHeading from "../components/shared/ContentHeading.vue";
import { useRoute } from "vue-router";
const route = useRoute(); // <--- this is the magic line
const catRoute = route.params.name; // (it is reactive)


console.log(route.params.id)

const header =
  {
    header: "Welcome to Gallry.Art",
    subHeader: "Looking for some cool new images to use?  Need some design inspiration? Check out these images generated by AI, awesome for all sorts of purposes. Whether you want to use them as illustrations, icons, or profile pics, there's no wrong way to go about it. And since they're free to use, there's no harm in giving them a try.",
  }


</script>
