<template>
  <section class="mx-auto max-w-max flex">
    <img class="h-20 pt-2 mr-2 mx-auto hidden md:flex" :src="avatar" />
    <div class="ml-1">
      <ContentHeading :heading="header" />
      <BigButtons />
      <TheGalleries />
    </div>
  </section>
</template>

<script setup>
import { ref } from "vue";
import BigButtons from "../components/shared/BigButtons.vue";
import ContentHeading from "../components/shared/ContentHeading.vue";
import TheGalleries from "../components/galleries/TheGalleries.vue";
const avatar = ref("https://imagedelivery.net/jUv0WjkQAcJxE0kRYIap3Q/794827e6-86ba-4863-23eb-bbfdf688f200/public");
const header =
{
  header: "Welcome to Gallry.Art",
  subHeader: "Looking for some cool new images to use?  Need some design inspiration? Check out these images generated by AI, awesome for all sorts of purposes. Whether you want to use them as illustrations, icons, or profile pics, there's no wrong way to go about it. And since they're free to use, there's no harm in giving them a try.",
}
</script>
