<template>
  <section class="mx-auto max-w-max flex">
    <img class="h-20 pt-2 mr-2 mx-auto hidden md:flex" :src="avatar" />
    <div class="ml-1">
      <ContentHeading :heading="header" />
      <SearchForm />
      <BigButtons />
      <TheGalleries />
    </div>
  </section>
</template>

<script setup>
import { ref } from "vue";
import BigButtons from "../components/shared/BigButtons.vue";
import ContentHeading from "../components/shared/ContentHeading.vue";
import TheGalleries from "../components/galleries/TheGalleries.vue";
import SearchForm from "../components/shared/SearchForm.vue";
const avatar = ref("https://imagedelivery.net/jUv0WjkQAcJxE0kRYIap3Q/794827e6-86ba-4863-23eb-bbfdf688f200/public");
const header =
{
  header: "Welcome to Gallry.Art",
  subHeader: "This projected started off as a way to show off the backend API that I was creating and turned into a gallery of AI generated images.  Much of the text content was also generated by AI. It's fun as design inspiration - check out these images generated by AI, awesome for all sorts of purposes. Whether you want to use them as illustrations, icons, or profile pics - they are all free to use.  Voting on the images is also a great way to help the AI learn and improve.  The more you vote, the better the AI gets.  Enjoy!",
}
</script>
